# Generated by Django 4.2.7 on 2023-11-11 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comparison_tool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparison_tool.customuser'),
        ),
        migrations.AlterField(
            model_name='savedqueries',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparison_tool.customuser'),
        ),
    ]
