# Generated by Django 4.2.7 on 2023-11-11 23:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison_tool', '0002_customuser_alter_comments_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googletrendsdata',
            name='date',
        ),
        migrations.RemoveField(
            model_name='googletrendsdata',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='googletrendsdata',
            name='search_volume',
        ),
        migrations.AddField(
            model_name='googletrendsdata',
            name='first_country',
            field=models.CharField(default='Colombia', max_length=100),
        ),
        migrations.AddField(
            model_name='googletrendsdata',
            name='first_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 11, 23, 41, 3, 726950, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='googletrendsdata',
            name='querie_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='googletrendsdata',
            name='second_country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='googletrendsdata',
            name='second_date',
            field=models.DateField(null=True),
        ),
    ]
