# Generated by Django 4.2.7 on 2023-11-14 01:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison_tool', '0003_remove_googletrendsdata_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedqueries',
            name='query_reference',
        ),
        migrations.AddField(
            model_name='savedqueries',
            name='first_country',
            field=models.CharField(default='Colombia', max_length=100),
        ),
        migrations.AddField(
            model_name='savedqueries',
            name='first_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 14, 1, 2, 4, 928040, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='savedqueries',
            name='querie_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='savedqueries',
            name='second_country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='savedqueries',
            name='second_date',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='GoogleTrendsData',
        ),
    ]
